# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='username')),
                ('activity_type', models.CharField(max_length=100, verbose_name='activity_type')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
