# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 13:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('activity_type', models.CharField(max_length=100, verbose_name='activity_type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('route', django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString, srid=4326, verbose_name='route')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        )
    ]
