# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Run',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='username',
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
