# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170410_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([(0, 0), (0, 0)]), srid=4326, verbose_name='route'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
