# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 21:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
import django.contrib.gis.geos.linestring
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170414_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='route',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(default=django.contrib.gis.geos.collections.MultiLineString(django.contrib.gis.geos.linestring.LineString([(0, 0), (0, 0)]), django.contrib.gis.geos.linestring.LineString([(0, 0), (0, 0)])), srid=4326, verbose_name='route'),
        ),
    ]
