# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 22:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170414_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='route',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(default=django.contrib.gis.geos.collections.MultiLineString, srid=4326, verbose_name='route'),
        ),
    ]
